# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 15:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('secretaryId', models.IntegerField(default=-1)),
                ('chiefId', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='Stuff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('workId', models.CharField(max_length=6)),
                ('phoneNumber', models.CharField(max_length=13)),
                ('icbcCard', models.CharField(max_length=16)),
                ('ccbCard', models.CharField(max_length=19)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='FiProcess.Department')),
            ],
        ),
    ]
