# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 09:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FiProcess', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stuff',
            name='password',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stuff',
            name='username',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stuff',
            name='ccbCard',
            field=models.CharField(blank=True, default='', max_length=19),
        ),
        migrations.AlterField(
            model_name='stuff',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FiProcess.Department'),
        ),
        migrations.AlterField(
            model_name='stuff',
            name='icbcCard',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
    ]
