# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 17:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FiProcess', '0003_stuffcheck'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FiProcess.Stuff')),
            ],
        ),
    ]
